# Generated by Django 3.1.7 on 2021-03-22 17:10

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('url', models.SlugField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('foto_post', models.ImageField(null=True, upload_to='foto_post/')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('post_data', models.DateField(auto_now_add=True, null=True)),
                ('post_update', models.DateField(auto_now=True)),
                ('images', models.ManyToManyField(related_name='post_image', to='pages.Image')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, related_name='rubrics', to='pages.rubric')),
            ],
        ),
    ]
